name: Metrics

on:
  schedule: [{cron: "0 0 * * 1"}] # S'executa cada dilluns a les 00:00
  workflow_dispatch:              # Permet executar-la manualment

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: XaviPerezCanada   # 👉 Canvia-ho pel teu usuari de GitHub
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
